### ISSUE TITLE
library installation issues

### ISSUE THREAD

**Issue by sanketh2222** [psastras/node-threadpool#7]
its a great library which offers similar functionalities as java , it would be great if you could help me resolve this issue.

C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\node_modules\aproba\index.js:25
    if (args[ii] == null) throw missingRequiredArg(ii)
                          ^

Error: Missing required argument #1
    at andLogAndFinish (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:31:3)
    at fetchPackageMetadata (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:51:22)      
    at resolveWithNewModule (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\install\deps.js:490:12)
    at C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\install\deps.js:491:7
    at C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\node_modules\iferr\index.js:13:50
    at C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:37:12
    at addRequestedAndFinish (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:67:5)      
    at returnAndAddMetadata (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:121:7)      
    at pickVersionFromRegistryDocument (C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\lib\fetch-package-metadata.js:138:20)
    at C:\Users\SankethS\.gitbook\versions\3.2.3\node_modules\npm\node_modules\iferr\index.js:13:50 {
  code: 'EMISSINGARG'
}
npm WARN bulk-match-scores@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-threadpool@1.5.5 postinstall: `gitbook install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-threadpool@1.5.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SankethS\AppData\Roaming\npm-cache\_logs\2022-12-21T12_48_56_602Z-debug.log
PS D:\09 August 2022\TEST\nodeJs> npm i node-threadpool --ignore-scripts
npm WARN bulk-match-scores@1.0.0 No repository field.

+ node-threadpool@1.5.5
added 2 packages from 2 contributors and audited 527 packages in 3.396s

4 packages are looking for funding
  run `npm fund` for details

found 197 vulnerabilities (7 low, 56 moderate, 116 high, 18 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
PS D:\09 August 2022\TEST\nodeJs> node .\multithread.js
internal/modules/cjs/loader.js:316
      throw err;
      ^

Error: Cannot find module 'D:\09 August 2022\TEST\nodeJs\node_modules\node-threadpool\dist\lib\node-threadpool.umd.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:308:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\09 August 2022\TEST\nodeJs\multithread.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\09 August 2022\\TEST\\nodeJs\\node_modules\\node-threadpool\\package.json',
  requestPath: 'node-threadpool'
}

**Comment by hhu8** [comment]
Same issue here. There is no directory "dist" after installation.

Error: Cannot find module '/homes/hhu8/tserver/node_modules/node-threadpool/dist/lib/node-threadpool.umd.js'. Please verify that the package.json has a valid "main" entry
